### ISSUE TITLE
Can't compile for Kernel 6.13.4 (Fedora 41 KDE)

### ISSUE THREAD

**Issue by lpgasparotto** [SimplyCEO/rtl8188eus#16]
Hi,
I worked with Kernel 6.12 but I can't compile with the new 6.13 version. 

```shell
os_dep/linux/ioctl_cfg80211.c:9456:32: error: inicialización de ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_chan_def *)’ desde un tipo de puntero ‘int (*)(struct wiphy *, struct cfg80211_chan_def *)’ incompatible [-Wincompatible-pointer-types]
 9456 |         .set_monitor_channel = cfg80211_rtw_set_monitor_channel,
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
os_dep/linux/ioctl_cfg80211.c:9456:32: nota: (cerca de la inicialización de ‘rtw_cfg80211_ops.set_monitor_channel’)
make[4]: *** [/usr/src/kernels/6.13.4-200.fc41.x86_64/scripts/Makefile.build:196: os_dep/linux/ioctl_cfg80211.o] Error 1
make[4]: *** Se espera a que terminen otras tareas....
make[3]: *** [/usr/src/kernels/6.13.4-200.fc41.x86_64/Makefile:2024: .] Error 2
make[2]: *** [/usr/src/kernels/6.13.4-200.fc41.x86_64/Makefile:263: __sub-make] Error 2
make[2]: se sale del directorio '/home/luispa/src/8188eu-git-Kernel612/rtl8188eus'
make[1]: *** [Makefile:263: __sub-make] Error 2
make[1]: se sale del directorio '/usr/src/kernels/6.13.4-200.fc41.x86_64'
make: *** [Makefile:2060: modules] Error 2
```

Thank you very much for this project.

**Comment by SimplyCEO** [comment]
I will take a look into it. Might be easy.

**Comment by lpgasparotto** [comment]
Thank you very much for your prompt reply.
